# Generated by Django 4.0.3 on 2023-10-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hats',
            name='name',
        ),
        migrations.AddField(
            model_name='hats',
            name='style',
            field=models.CharField(default='CAP', max_length=200),
        ),
    ]
