# Generated by Django 4.0.3 on 2023-10-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200)),
                ('closet_name', models.CharField(max_length=100)),
                ('bin_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(default='88', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='manufacturer',
            field=models.CharField(default='Sony', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='picture',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='bin',
            field=models.ForeignKey(default=88, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes_rest.binvo'),
            preserve_default=False,
        ),
    ]
