# Generated by Django 4.0.3 on 2023-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_binvo_shoe_color_shoe_manufacturer_shoe_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='bin',
            new_name='assigned_bin',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='manufacturer',
            new_name='manufacturer_name',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='name',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='picture',
            new_name='picture_url',
        ),
        migrations.RemoveField(
            model_name='binvo',
            name='bin_number',
        ),
        migrations.AlterField(
            model_name='binvo',
            name='closet_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
